version: '3'

services:
  database:
    build: 
      context: .
      dockerfile: Dockerfile_postgresql
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
     APP_ENV: dev
     APP_DEBUG: 1
     PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}
    depends_on:
      - database

  nginx:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    restart: on-failure
    depends_on:
      - php
    ports:
      - "8080:80"
      
# services:
#   postgres:
#     image: postgres:16-alpine
#     restart: on-failure
#     environment:
#       POSTGRES_DB: test
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: pass
#       PGDATA: /var/lib/postgres/data
#     volumes:
#       - ./db-data:/var/lib/postgresql/data:rw
#     ports:
#       - "5432:5432"  
#   php:
#     build: 
#       context: .
#     image: sf-docker/php:dev
#     restart: on-failure
#     environment:
#      APP_ENV: dev
#      APP_DEBUG: 1
#      PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}
#     depends_on:
#       - postgres

#   nginx:
#     build:
#      context: .
#     image: sf-docker/nginx:dev
#     restart: on-failure
#     depends_on:
#       - php
#     ports:
#       - "8080:80"
    



# #> doctrine/doctrine-bundle ###
#   database:
#     image: postgres:${POSTGRES_VERSION:-16}-alpine
#     environment:
#       POSTGRES_DB: ${POSTGRES_DB:-app}
#       # You should definitely change the password in production
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
#       POSTGRES_USER: ${POSTGRES_USER:-app}
#     volumes:
#       - database_data:/var/lib/postgresql/data:rw
#       # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
#       # - ./docker/db/data:/var/lib/postgresql/data:rw
# ###< doctrine/doctrine-bundle ###

# volumes:
# ###> doctrine/doctrine-bundle ###
#   database_data:
# ###< doctrine/doctrine-bundle ###
